[phases.setup]
packages = ["nodejs_18", "yarn-1_x", "openssl"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn run build"]

[phases.start]
cmds = ["NODE_ENV=production yarn run start"]
